language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  

script: 
  - pytest --cov
  - coverage # run --source=my_package setup.py test
  # - coverage


after_success:
  - coveralls
